{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.orivia",
    "module": "monetization",
    "version": "1.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "monetization-1.15.0.aar",
          "url": "monetization-1.15.0.aar",
          "size": 412126,
          "sha512": "330871bbd0fad1f1e21ce34ca922944898f8d241e08e92f573a41d4826d93603da8dbd551163d2c7f9a1eae5200636caff9db28a1ff76636ae980d4d1e384336",
          "sha256": "8cb20a0dbb8db7f0461c160a21585b44566f5a238f9114eec72eec26cb510409",
          "sha1": "82819a7b83f6b2d553d6bd4d72408d6479241ac4",
          "md5": "360511d3ad923c46ae2a489165aa36e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "monetization-1.15.0.aar",
          "url": "monetization-1.15.0.aar",
          "size": 412126,
          "sha512": "330871bbd0fad1f1e21ce34ca922944898f8d241e08e92f573a41d4826d93603da8dbd551163d2c7f9a1eae5200636caff9db28a1ff76636ae980d4d1e384336",
          "sha256": "8cb20a0dbb8db7f0461c160a21585b44566f5a238f9114eec72eec26cb510409",
          "sha1": "82819a7b83f6b2d553d6bd4d72408d6479241ac4",
          "md5": "360511d3ad923c46ae2a489165aa36e6"
        }
      ]
    }
  ]
}
