{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.orivia",
    "module": "monetization-unity-bridge",
    "version": "1.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "monetization-unity-bridge-1.16.0.aar",
          "url": "monetization-unity-bridge-1.16.0.aar",
          "size": 15549,
          "sha512": "a05ffcb135397b837e1111c651d0d8d9cc0013cb90c8def5fbd2735396c0057806b68d435506c48c88d3c243bdddbc8c31d6d3500b96fe217b8aa7385da1bb70",
          "sha256": "33a8d6c898c2d5be5b20f99a5e774feae6025af2915095752ae35c3aff981326",
          "sha1": "a8de4a9cfe044ff6d44c22110a929f7878a4ec23",
          "md5": "627e741f0b767b05d47f53ae9a067568"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "monetization-unity-bridge-1.16.0.aar",
          "url": "monetization-unity-bridge-1.16.0.aar",
          "size": 15549,
          "sha512": "a05ffcb135397b837e1111c651d0d8d9cc0013cb90c8def5fbd2735396c0057806b68d435506c48c88d3c243bdddbc8c31d6d3500b96fe217b8aa7385da1bb70",
          "sha256": "33a8d6c898c2d5be5b20f99a5e774feae6025af2915095752ae35c3aff981326",
          "sha1": "a8de4a9cfe044ff6d44c22110a929f7878a4ec23",
          "md5": "627e741f0b767b05d47f53ae9a067568"
        }
      ]
    }
  ]
}
